'use client';

import { X } from 'lucide-react';

import { formatHumanDate, formatTime } from '@/utils/datetime';
import {
  REPORT_STATS,
  type EmergencyReportCatalogEntry,
} from '@/features/emergency/__mocks__/emergencyReportsFixtures';

const FOCUS_RING =
  'focus-visible:ring-2 focus-visible:ring-[#00B4D8]/50 focus-visible:outline-none';

export function ReportPreviewModal({
  report,
  onClose,
  onDownload,
}: {
  report: EmergencyReportCatalogEntry;
  onClose: () => void;
  onDownload: () => void;
}) {
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(13,38,48,0.45)' }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        className="flex w-full flex-col overflow-hidden bg-white"
        style={{ maxWidth: 560, borderRadius: 16, maxHeight: '85vh' }}
      >
        <div
          className="flex shrink-0 items-start justify-between gap-3 px-6 py-5"
          style={{ borderBottom: '1px solid rgba(0,100,130,0.12)' }}
        >
          <div>
            <h2 className="font-display font-semibold" style={{ fontSize: 20, color: '#0D2630' }}>
              {report.name}
            </h2>
            <p className="mt-0.5" style={{ fontSize: 14, color: '#4A7080' }}>
              {report.dateRangeLabel} · {report.format}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className={`flex size-11 shrink-0 items-center justify-center rounded-full transition-colors duration-150 hover:bg-[rgba(0,0,0,0.06)] ${FOCUS_RING}`}
          >
            <X style={{ width: 20, height: 20, color: '#4A7080' }} />
          </button>
        </div>

        <div className="overflow-y-auto scroll-smooth px-6 py-5">
          <p style={{ fontSize: 14, color: '#4A7080' }}>{report.description}</p>

          <div className="mt-3 grid grid-cols-2 gap-3">
            <div>
              <p style={{ fontSize: 14, color: '#8A98A3' }}>Generated By</p>
              <p className="font-sans font-medium" style={{ fontSize: 14, color: '#0D2630' }}>
                {report.generatedBy}
              </p>
            </div>
            <div>
              <p style={{ fontSize: 14, color: '#8A98A3' }}>Generated On</p>
              <p className="font-sans font-medium" style={{ fontSize: 14, color: '#0D2630' }}>
                {formatHumanDate(report.generatedOn)}, {formatTime(report.generatedOn)}
              </p>
            </div>
            <div>
              <p style={{ fontSize: 14, color: '#8A98A3' }}>Location</p>
              <p className="font-sans font-medium" style={{ fontSize: 14, color: '#0D2630' }}>
                {report.location}
              </p>
            </div>
            <div>
              <p style={{ fontSize: 14, color: '#8A98A3' }}>Shift</p>
              <p className="font-sans font-medium" style={{ fontSize: 14, color: '#0D2630' }}>
                {report.shift}
              </p>
            </div>
          </div>

          <p className="mt-4 font-sans font-medium" style={{ fontSize: 14, color: '#0D2630' }}>
            Key Metrics Snapshot
          </p>
          <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">
            {REPORT_STATS.map((s) => (
              <div key={s.key} className="rounded-[10px] p-2.5" style={{ background: '#F5FBFD' }}>
                <p style={{ fontSize: 14, color: '#8A98A3' }}>{s.label}</p>
                <p
                  className="font-display font-semibold"
                  style={{ fontSize: 16, color: '#0D2630' }}
                >
                  {s.value}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div
          className="flex shrink-0 items-center justify-end gap-2.5 px-6 py-4"
          style={{ borderTop: '1px solid rgba(0,100,130,0.12)' }}
        >
          <button
            type="button"
            onClick={onClose}
            className={`flex h-11 items-center gap-1.5 rounded-[10px] px-4 font-sans font-medium transition-colors duration-150 hover:bg-[#F5FBFD] ${FOCUS_RING}`}
            style={{ fontSize: 14, color: '#0D2630', border: '1px solid rgba(0,100,130,0.2)' }}
          >
            Close
          </button>
          <button
            type="button"
            onClick={onDownload}
            className={`flex h-11 items-center gap-1.5 rounded-[10px] px-4 font-sans font-medium text-white transition-opacity duration-150 hover:opacity-90 ${FOCUS_RING}`}
            style={{ fontSize: 14, background: '#0D2630' }}
          >
            Download
          </button>
        </div>
      </div>
    </div>
  );
}
